In [1]:
# packages

import numpy as np
import matplotlib as mpl
mpl.rcParams['axes.formatter.useoffset'] = False
import matplotlib.pyplot as plt
import scipy

from scipy.signal import sawtooth, square, savgol_filter
import pandas as pd
import glob as gl
import os
import cmath

from scipy.signal import sawtooth, square,find_peaks, savgol_filter
from scipy import spatial
#import lambdafit as lf
from scipy.interpolate import CubicSpline,interp1d
import h5py

from tqdm import tqdm as tqdm_terminal
from tqdm.notebook import trange, tqdm_notebook
from scipy.signal.windows import hann

from scipy.fft import fft, ifft, fftfreq
from copy import deepcopy
from scipy.interpolate import CubicSpline, interp1d
from scipy.optimize import curve_fit

# for pandas visual number display 

pd.set_option('display.precision', 6)
pd.set_option('display.float_format', '{:.10f}'.format)

# import ali_offline_demod.py 

import ali_offline_demod as aod

import time_chunking_functions as tcf

#### Now trying out time chunking functions but at larger scale...

In [2]:
# data file

# LO: 4250
ts_LO4250_1 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4250.0_20240308061355_t_20240308062133/ts_toneinit_fcenter_4250.0_20240308061355_t_20240308062147.hd5'
ts_LO4250_1_fn = 'ts_toneinit_fcenter_4250.0_20240308061355_t_20240308062147.hd5'
t_xy_LO4250_1 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4250.0_20240308061355_t_20240308062133/beam_map_data_20240308062147.txt'
ts_LO4250_1_PATH = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4250.0_20240308061355_t_20240308062133'

ts_LO4250_2 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4250.0_20240307141217_t_20240307141951/ts_toneinit_fcenter_4250.0_20240307141217_t_20240307142007.hd5'
ts_LO4250_2_fn = 'ts_toneinit_fcenter_4250.0_20240307141217_t_20240307142007.hd5' 
t_xy_LO4250_2 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4250.0_20240307141217_t_20240307141951/beam_map_data_20240307142007.txt'
ts_LO4250_2_PATH = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4250.0_20240307141217_t_20240307141951'

# LO: 4750

ts_LO4750_1 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4750.0_20240309114324_t_20240309120414/ts_toneinit_fcenter_4750.0_20240309114324_t_20240309120429.hd5'
ts_LO4750_1_fn = 'ts_toneinit_fcenter_4750.0_20240309114324_t_20240309120429.hd5'
t_xy_LO4750_1 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4750.0_20240309114324_t_20240309120414/beam_map_data_20240309120429.txt'
ts_LO4750_1_PATH = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4750.0_20240309114324_t_20240309120414'

ts_LO4750_2 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4750.0_20240310035539_t_20240310040323/ts_toneinit_fcenter_4750.0_20240310035539_t_20240310040333.hd5'
ts_LO4750_2_fn = 'ts_toneinit_fcenter_4750.0_20240310035539_t_20240310040333.hd5'
t_xy_LO4750_2 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4750.0_20240310035539_t_20240310040323/beam_map_data_20240310040333.txt'
ts_LO4750_2_PATH = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4750.0_20240310035539_t_20240310040323'

ts_LO4750_3 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4750.0_20240310185738_t_20240310190410/ts_toneinit_fcenter_4750.0_20240310185738_t_20240310190423.hd5'
ts_LO4750_3_fn = 'ts_toneinit_fcenter_4750.0_20240310185738_t_20240310190423.hd5'
t_xy_LO4750_3 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4750.0_20240310185738_t_20240310190410/beam_map_data_20240310190423.txt'
ts_LO4750_3_PATH = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_4750.0_20240310185738_t_20240310190410'

# LO: 5250

ts_LO5250_1 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5250.0_20240311125818_t_20240311130516/ts_toneinit_fcenter_5250.0_20240311125818_t_20240311130530.hd5'
ts_LO5250_1_fn = 'ts_toneinit_fcenter_5250.0_20240311125818_t_20240311130530.hd5'
t_xy_LO5250_1 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5250.0_20240311125818_t_20240311130516/beam_map_data_20240311130530.txt'
ts_LO5250_1_PATH = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5250.0_20240311125818_t_20240311130516'

ts_LO5250_2 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5250.0_20240312134539_t_20240312135047/ts_toneinit_fcenter_5250.0_20240312134539_t_20240312135056.hd5'
ts_LO5250_2_fn = 'ts_toneinit_fcenter_5250.0_20240312134539_t_20240312135056.hd5'
t_xy_LO5250_2 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5250.0_20240312134539_t_20240312135047/beam_map_data_20240312135056.txt'
ts_LO5250_2_PATH = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5250.0_20240312134539_t_20240312135047'

ts_LO5250_3 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5250.0_20240313105637_t_20240313110245/ts_toneinit_fcenter_5250.0_20240313105637_t_20240313110254.hd5'
ts_LO5250_3_fn = 'ts_toneinit_fcenter_5250.0_20240313105637_t_20240313110254.hd5'
t_xy_LO5250_3 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5250.0_20240313105637_t_20240313110245/beam_map_data_20240313110254.txt'
ts_LO5250_3_PATH = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5250.0_20240313105637_t_20240313110245'

# LO: 5750

ts_LO5750_1 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5750.0_20240314100519_t_20240314101210/ts_toneinit_fcenter_5750.0_20240314100519_t_20240314101219.hd5'
ts_LO5750_1_fn = 'ts_toneinit_fcenter_5750.0_20240314100519_t_20240314101219.hd5'
t_xy_LO5750_1 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5750.0_20240314100519_t_20240314101210/beam_map_data_20240314101219.txt'
ts_LO5750_1_PATH = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5750.0_20240314100519_t_20240314101210'

ts_LO5750_2 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5750.0_20240318183441_t_20240318184103/ts_toneinit_fcenter_5750.0_20240318183441_t_20240318184325.hd5'
ts_LO5750_2_fn = 'ts_toneinit_fcenter_5750.0_20240318183441_t_20240318184325.hd5'
t_xy_LO5750_2 = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5750.0_20240318183441_t_20240318184103/beam_map_data_20240318184325.txt'
ts_LO5750_2_PATH = '/home/matt/ali_drive_mnt/beam_map_data/toneinit_fcenter_5750.0_20240318183441_t_20240318184103'

#### Now: process is to first get them in time-chunked state, then apply the modified full_demod_process function from the imported script

In [3]:
freq_list_ex_path = '/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240308061355/freq_list_lo_sweep_targeted_1_fcenter_4250.0_20240308061555.npy'
freq_list_ex = np.load(freq_list_ex_path)
freq_list_4250_1 = pd.DataFrame(freq_list_ex)

In [6]:
freq_list_4250_1.loc[102:105]


#[4.22706738e+09+0.j 4.23421203e+09+0.j 4.23441903e+09+0.j
 #4.23421509e+09+0.j]

                                      0
102 4227067382.8125510216+0.0000000000j
103 4234212031.2500519753+0.0000000000j
104 4234419031.2500939369+0.0000000000j
105 4234215085.9375104904+0.0000000000j

In [12]:
5667/2

2833.5

In [20]:
t_xy_5250_2_read = pd.read_csv(t_xy_LO5250_2, sep=',')
t_xy_5250_2_read

                     start                   end   x    y
0    1710276658.1760025024 1710276908.4819543362   0    0
1    1710276910.4842259884 1710276913.9611761570  10    0
2    1710276915.9618194103 1710276919.4384434223  20    0
3    1710276921.4406118393 1710276924.9182603359  30    0
4    1710276926.9205005169 1710276930.3969514370  40    0
...                    ...                   ...  ..  ...
5771 1710308531.3297669888 1710308534.8073728085  40  750
5772 1710308536.8097252846 1710308540.2877576351  30  750
5773 1710308542.2899904251 1710308545.7689018250  20  750
5774 1710308547.7712430954 1710308551.2482705116  10  750
5775 1710308553.2505629063 1710308556.7281901836   0  750

[5776 rows x 4 columns]

In [23]:
find = t_xy_5250_2_read[(t_xy_5250_2_read[' x']==370) & (t_xy_5250_2_read[' y']==370)]# & t_xy_5250_2_read[' y']==375)
find

                     start                   end    x    y
2850 1710292523.8314507008 1710292527.3094482422  370  370

In [7]:
t_4250_1, I_4250_1, Q_4250_1 = tcf.get_ts_chunks_time_indexing(ts_LO4250_1, t_xy_LO4250_1, chunk='some', chunk_start=102, chunk_stop=105, 
                                                               single_channel=None, time_chunk_index_start=1000, time_chunk_index_stop=1005)

4
[-1379 -1567 -1765 ... -1448 -1426 -1764]
[1.70990771e+09 1.70990796e+09 1.70990797e+09]
[1.70990796e+09 1.70990797e+09 1.70990797e+09]
True

In [27]:
def time_chunk_index_demod_plot(ts_filename, t_xy_file, chunk='some', chunk_start=None, chunk_stop=None, 
                                single_channel=None, time_chunk_index_start=0, time_chunk_index_stop=10,
                                ts_path='ts_path', ts_short_filename='ts_short_filename', 
                                tone_init_path='/home/matt/ali_drive_mnt/tone_initializations', 
                                plot_spacing=0.01):
    
    t, I, Q, t_xy_table = tcf.get_ts_chunks_time_indexing(ts_filename=ts_filename, t_xy_file=t_xy_file, chunk=chunk, chunk_start=chunk_start, 
                                                          chunk_stop=chunk_stop, single_channel=None, time_chunk_index_start=time_chunk_index_start,
                                                          time_chunk_index_stop=time_chunk_index_stop)
    
    chunks_demodulated = []

    for i in range(len(t)):
        t_chunked = t[i]
        i_chunked = np.array(I[i])
        q_chunked = np.array(Q[i])
        demodulated_chunk = tcf.modified_demod_process_for_tchunks(t_chunked, i_chunked, q_chunked, ts_file=ts_short_filename, f_sawtooth=15, method='fft', 
                                                                   correct_phase_jumps=False, phase_jump_threshold=0.4, n=0, channels=chunk,
                                                                   start_channel=chunk_start, stop_channel=chunk_stop, tone_init_path=tone_init_path,
                                                                   ts_path=ts_path, display_mode='notebook')
        chunks_demodulated.append(demodulated_chunk)

        plt.figure(figsize=(5,10))
        for j in range(len(demodulated_chunk['demod data'])):
            plt.plot(demodulated_chunk['demod t'], demodulated_chunk['demod data'][j] + plot_spacing*j, label=f'channel {chunk_start+j}')
            # plt.legend()
            plt.title(f'Time Chunk {time_chunk_index_start + i}')

    return chunks_demodulated, t_xy_table

In [8]:
%matplotlib qt

# actually testing 3 (bias line 12?)
testing_5250_1 = time_chunk_index_demod_plot(ts_LO5250_3, t_xy_LO5250_3, chunk='some', chunk_start=170, chunk_stop=220,
                                             time_chunk_index_start=3000, time_chunk_index_stop=3030, ts_path=ts_LO5250_3_PATH, 
                                             ts_short_filename=ts_LO5250_3_fn, tone_init_path='/home/matt/ali_drive_mnt/tone_initializations', 
                                             plot_spacing=0.1)

51
[-1628 -1991 -2281 ... -2025 -1715 -2208]
[1.71035298e+09 1.71035323e+09 1.71035323e+09]
[1.71035323e+09 1.71035323e+09 1.71035324e+09]
True
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.521903527012781-0.853004518447364j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9695024250199127+0.24508171674057722j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.4821260096873843+0.8761018837914459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j

/home/matt/readout/lea_beammap_work/ali_hdf5_reading/time_chunking/ali_offline_demod.py:1393: RuntimeWarning: divide by zero encountered in log10
  y=np.append(y,20*np.log10(np.abs(test_sweep[1,:])))

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (979,)
len t: 979
len t_fr_start: 963
len sig_fr_start: 963
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
shape sig: (977,)
len t: 977
len t_fr_start: 949
len sig_fr_start: 949
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (977,)
len t: 977
len t_fr_start: 952
len sig_fr_start: 952
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region

/tmp/ipykernel_1669046/4290339337.py:23: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure(figsize=(5,10))

start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.521903527012781-0.853004518447364j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9695024250199127+0.24508171674057722j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.4821260096873843+0.8761018837914459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.38085467583742233+0.9246349095144375j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (977,)
len t: 977
len t_fr_start: 970
len sig_fr_start: 970
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
shape sig: (977,)
len t: 977
len t_fr_start: 971
len sig_fr_start: 971
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (977,)
len t: 977
len t_fr_start: 948
len sig_fr_start: 948
using full_demod_process
5250.0
20240313105637
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240313105637/
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
num of channels: 51
num of tones: 51
looking for delay region
start = 5119999187.500001
stop = 5130019695.312501
delay: 6.494839924046016e-08
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.26603578583130083+0.9639631531636063j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.13346981820609002+0.9910528783208459j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4284170485645931+0.9035811156167458j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4828905242215612+0.8756807304132174j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.4348273675379942+0.9005138313429606j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.49016865450385116+0.8716276097863607j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.12553292058972532-0.9920894545595239j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.9856522694910494+0.16878863601304325j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(0.40741881026471505+0.9132414319567878j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.33940870053695016+0.9406390030185964j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8984118547672664+0.43915389012695794j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.8943059475464987-0.4474560002759591j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.6295072809503-0.7769945837845719j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j
 5.44053127e+09+0.j 5.44185296e+09+0.j 5.44242457e+09+0.j
 5.44332450e+09+0.j 5.44428197e+09+0.j 5.44447497e+09+0.j
 5.44432640e+09+0.j 5.44450240e+09+0.j 5.44963151e+09+0.j
 5.45179564e+09+0.j 5.45372463e+09+0.j 5.45668290e+09+0.j
 5.45819592e+09+0.j 5.45970959e+09+0.j 5.46194291e+09+0.j
 5.46338530e+09+0.j 5.46414744e+09+0.j 5.46588237e+09+0.j
 5.46826609e+09+0.j 5.46970290e+09+0.j 5.47009035e+09+0.j
 5.47184447e+09+0.j 5.47414916e+09+0.j 5.47623807e+09+0.j
 5.47802779e+09+0.j 5.47990690e+09+0.j 5.48159803e+09+0.j
 5.48487520e+09+0.j 5.48552272e+09+0.j 5.48815137e+09+0.j
 5.48836537e+09+0.j 5.49035497e+09+0.j 5.49036656e+09+0.j]
(-0.1684713953135241-0.9857065430244005j)
6.494839924046016e-08
[5.40747959e+09+0.j 5.40846749e+09+0.j 5.40922438e+09+0.j
 5.40937438e+09+0.j 5.40924179e+09+0.j 5.40939479e+09+0.j
 5.41614630e+09+0.j 5.42010268e+09+0.j 5.42250800e+09+0.j
 5.42438486e+09+0.j 5.42627137e+09+0.j 5.42852232e+09+0.j
 5.42956613e+09+0.j 5.43081989e+09+0.j 5.43258022e+09+0.j
 5.43569066e+09+0.j 5.43770034e+09+0.j 5.43989058e+09+0.j

  0%|          | 0/51 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952

In [25]:
# bias line 9?
tchunk_5250_2_demod = time_chunk_index_demod_plot(ts_LO5250_2, t_xy_LO5250_2, chunk='some', chunk_start=105, chunk_stop=140,
                                                  time_chunk_index_start=2840, time_chunk_index_stop=2860, ts_path=ts_LO5250_2_PATH, 
                                                  ts_short_filename=ts_LO5250_2_fn, tone_init_path='/home/matt/ali_drive_mnt/tone_initializations', 
                                                  plot_spacing=1)

# run this -- a lot going on here. can't see chop but definitely response

36
[422 383 410 ... 403 430 361]
[1.71027666e+09 1.71027691e+09 1.71027692e+09]
[1.71027691e+09 1.71027692e+09 1.71027692e+09]
True
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.24426232982839138+0.9697091905446736j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6657695375884435+0.7461574383595395j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9657562221429421+0.2594511888432816j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j

/home/matt/readout/lea_beammap_work/ali_hdf5_reading/time_chunking/ali_offline_demod.py:1393: RuntimeWarning: divide by zero encountered in log10
  y=np.append(y,20*np.log10(np.abs(test_sweep[1,:])))

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (975,)
len t: 975
len t_fr_start: 955
len sig_fr_start: 955
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (975,)
len t: 975
len t_fr_start: 961
len sig_fr_start: 961
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
num of channels: 36
num of tones: 36
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.06300106307525112+0.9980134598548199j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.7889759065103055+0.6144241360381619j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9879903228863811+0.15451576580680804j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9411571379039525-0.3379692911677636j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.657177244758133-0.7537360738163651j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6028061943557356-0.7978876437483884j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6538875423349952-0.7565917538402727j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.6007398636469451-0.7994445673249959j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.48729742510726265-0.8732360617174669j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.392100969241056+0.9199221868833388j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.15037745287665344+0.9886286571136454j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.8993463127864756+0.43723701773451296j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.9366143919760695-0.3503619282160913j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5831742208321958-0.8123471106348328j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5188459453023642-0.8548677588044225j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5861163877779388-0.8102268694496257j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(-0.5225461907716397-0.8526109772399422j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.028696691078482498-0.999588165156604j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.22261947747234073-0.9749054150274999j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.9496131928347379+0.3134242874989347j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j
 5.36826748e+09+0.j 5.36962914e+09+0.j 5.37126793e+09+0.j
 5.37224828e+09+0.j 5.37930574e+09+0.j 5.37951874e+09+0.j
 5.37953074e+09+0.j 5.38001277e+09+0.j 5.38001677e+09+0.j
 5.38001877e+09+0.j 5.38002467e+09+0.j 5.38002767e+09+0.j
 5.38051574e+09+0.j 5.38354918e+09+0.j 5.38415706e+09+0.j]
(0.39444124310724415+0.9189211640483703j)
5.6310396935252216e-08
[5.33187445e+09+0.j 5.33462221e+09+0.j 5.33605383e+09+0.j
 5.33746673e+09+0.j 5.33890527e+09+0.j 5.33910327e+09+0.j
 5.33891759e+09+0.j 5.33911059e+09+0.j 5.33949338e+09+0.j
 5.34867255e+09+0.j 5.34938470e+09+0.j 5.35297201e+09+0.j
 5.35526274e+09+0.j 5.35693090e+09+0.j 5.35714890e+09+0.j
 5.35692065e+09+0.j 5.35713665e+09+0.j 5.35877181e+09+0.j
 5.35932522e+09+0.j 5.36403141e+09+0.j 5.36642406e+09+0.j

  0%|          | 0/36 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960

In [28]:
tchunk_5250_2_demod = time_chunk_index_demod_plot(ts_LO5250_2, t_xy_LO5250_2, chunk='some', chunk_start=177, chunk_stop=195,
                                                  time_chunk_index_start=2840, time_chunk_index_stop=2860, ts_path=ts_LO5250_2_PATH, 
                                                  ts_short_filename=ts_LO5250_2_fn, tone_init_path='/home/matt/ali_drive_mnt/tone_initializations', 
                                                  plot_spacing=1)

19
[745 693 718 ... 754 725 734]
[1.71027666e+09 1.71027691e+09 1.71027692e+09]
[1.71027691e+09 1.71027692e+09 1.71027692e+09]
True
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
1.6276041666666667
n_phi0: 1.6276041666666667
start index: 14

/home/matt/readout/lea_beammap_work/ali_hdf5_reading/time_chunking/ali_offline_demod.py:1393: RuntimeWarning: divide by zero encountered in log10
  y=np.append(y,20*np.log10(np.abs(test_sweep[1,:])))

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.712673611111108
n_phi0: 2.712673611111108
start index: 18

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.244971264367816
n_phi0: 2.244971264367816
start index: 15

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.325148809523816
n_phi0: 2.325148809523816
start index: 19

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.034505208333339
n_phi0: 2.034505208333339
start index: 19

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (976,)
len t: 976
len t_fr_start: 957
len sig_fr_start: 957
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.170138888888899
n_phi0: 2.170138888888899
start index: 14

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.325148809523807
n_phi0: 2.325148809523807
start index: 20

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
1.9728535353535361
n_phi0: 1.9728535353535361
start index: 12

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.325148809523816
n_phi0: 2.325148809523816
start index: 15

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.504006410256412
n_phi0: 2.504006410256412
start index: 18

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.325148809523807
n_phi0: 2.325148809523807
start index: 17

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.5040064102564084
n_phi0: 2.5040064102564084
start index: 12

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.504006410256412
n_phi0: 2.504006410256412
start index: 13

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.3251488095238093
n_phi0: 2.3251488095238093
start index: 11

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.170138888888883
n_phi0: 2.170138888888883
start index: 19

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.034505208333339
n_phi0: 2.034505208333339
start index: 18

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (976,)
len t: 976
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.504006410256407
n_phi0: 2.504006410256407
start index: 17

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (975,)
len t: 975
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.3251488095238093
n_phi0: 2.3251488095238093
start index: 9

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
1.9148284313725514
n_phi0: 1.9148284313725514
start index: 19

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
5250.0
20240312134539
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5250.0_20240312134539/
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
num of channels: 19
num of tones: 19
looking for delay region
start = 5120499164.062501
stop = 5130519671.875001
delay: 5.6310396935252216e-08
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.6945903583597489-0.7194054726464594j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9994315688724728-0.0337125961786947j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8073537257587444+0.5900677600949523j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.10816815288804302+0.9941326122307773j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.589617515452191+0.8076826019371628j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9196435547848345+0.3927540351705035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9165811565915105-0.39984870061233035j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.3753249489686207-0.9268932962761691j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.22603734066533504-0.9741186378593437j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.8763260684742223-0.48171840499664587j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9999906509772404+0.00432411356407162j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.9879731527201597+0.154625513755615j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.7214615836706755+0.6924544629702382j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(0.0025273605608684144+0.9999968062191976j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.20101793171593493+0.9795875617465994j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.6849114746336502+0.7286262909854123j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.9825778642368942+0.18585139416120486j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.8888895629357635-0.45812153944544826j)
5.6310396935252216e-08
[5.44965448e+09+0.j 5.45182862e+09+0.j 5.45370777e+09+0.j
 5.45666992e+09+0.j 5.45814588e+09+0.j 5.45966248e+09+0.j
 5.46196591e+09+0.j 5.46415551e+09+0.j 5.46588739e+09+0.j
 5.46826205e+09+0.j 5.46969485e+09+0.j 5.47012142e+09+0.j
 5.47184449e+09+0.j 5.47411516e+09+0.j 5.47469436e+09+0.j
 5.47625477e+09+0.j 5.47803363e+09+0.j 5.47990701e+09+0.j
 5.48157284e+09+0.j]
(-0.4842697885788313-0.8749187230079226j)
shape_cals: (19, 3)
[-1481.35835764-1444.52933366j  1258.26205688   +0.j
    -2.31483998   +0.j        ]
2.24497126436782
n_phi0: 2.24497126436782
start index: 16

  0%|          | 0/19 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961

in 5750_1, channels: 
- 164
- 190
- chunk 2847 channel 165???

In [29]:
tchunk_5750_1_demod = time_chunk_index_demod_plot(ts_LO5750_1, t_xy_LO5750_1, chunk='some', chunk_start=164, chunk_stop=193, 
                                                  time_chunk_index_start=2840, time_chunk_index_stop=2860, ts_path=ts_LO5750_1_PATH, 
                                                  ts_short_filename=ts_LO5750_1_fn, tone_init_path='/home/matt/ali_drive_mnt/tone_initializations', 
                                                  plot_spacing=1)

30
[1598  642 1018 ... 1727 1750 1613]
[1.71043634e+09 1.71043659e+09 1.71043660e+09]
[1.71043659e+09 1.71043660e+09 1.71043660e+09]
True
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.659529204982572+0.7516789392919404j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.11681907753653202+0.9931532123109272j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5881956672832737+0.80871865131774j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j

/home/matt/readout/lea_beammap_work/ali_hdf5_reading/time_chunking/ali_offline_demod.py:1393: RuntimeWarning: divide by zero encountered in log10
  y=np.append(y,20*np.log10(np.abs(test_sweep[1,:])))

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
shape sig: (976,)
len t: 976
len t_fr_start: 970
len sig_fr_start: 970
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (976,)
len t: 976
len t_fr_start: 966
len sig_fr_start: 966
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (976,)
len t: 976
len t_fr_start: 972
len sig_fr_start: 972
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (977,)
len t: 977
len t_fr_start: 961
len sig_fr_start: 961
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
shape sig: (977,)
len t: 977
len t_fr_start: 957
len sig_fr_start: 957
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
using full_demod_process
5750.0
20240314100519
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240314100519/
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
num of channels: 30
num of tones: 30
looking for delay region
start = 5695468578.125067
stop = 5705489085.937567
delay: 6.489387703471064e-08
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.25463343046039955+0.9670376497799705j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.6450513592997291+0.7641392175942626j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9999059591471241-0.013713965949706986j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7233353503241137-0.690496901493042j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.710013932159614-0.7041876285048205j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.3863211389844199+0.9223643410137777j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.13284397679879326+0.9911369621945706j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.7727048068902416+0.6347655326250116j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9661986015505164-0.25779887967527393j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.48441652952950665-0.8748374854329166j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.18303526778137988-0.9831063476288812j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8675081157307619-0.4974230283584215j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.8501490518427841+0.5265421062467989j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.5095377014211334+0.8604483312962307j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.20207280211488698+0.9793705032547375j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9718755284002739-0.23549513221442236j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.539182730747993-0.8421888047600354j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.10383426099917466-0.9945946140225953j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.834917854158746-0.5503745786343651j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.9905785391032249+0.13694582092243876j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.0509852621572292+0.998699405748676j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.5529777637286134+0.8331960110452413j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.9862900824301293+0.1650208268673041j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(-0.738165680310958-0.6746194693388715j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.026503045157395738-0.9996487326043009j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j
 5.93412312e+09+0.j 5.93530431e+09+0.j 5.93711459e+09+0.j
 5.94105104e+09+0.j 5.94292380e+09+0.j 5.94457556e+09+0.j
 5.94674352e+09+0.j 5.94850981e+09+0.j 5.95215043e+09+0.j
 5.95346236e+09+0.j 5.95547120e+09+0.j 5.95769376e+09+0.j
 5.95979523e+09+0.j 5.96166439e+09+0.j 5.96566880e+09+0.j
 5.96772227e+09+0.j 5.96897733e+09+0.j 5.97099770e+09+0.j]
(0.7093950899532315-0.704811043010995j)
6.489387703471064e-08
[5.87434501e+09+0.j 5.87669591e+09+0.j 5.87886254e+09+0.j
 5.88069817e+09+0.j 5.91156457e+09+0.j 5.92023301e+09+0.j
 5.92153255e+09+0.j 5.92337160e+09+0.j 5.92569771e+09+0.j
 5.92767043e+09+0.j 5.92936212e+09+0.j 5.93148626e+09+0.j

  0%|          | 0/30 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966

for these: 
- channel 121/122? 
- channel 135
- channel 20 chunk 2843

In [30]:
tchunk_5750_2_demod = time_chunk_index_demod_plot(ts_LO5750_2, t_xy_LO5750_2, chunk='some', chunk_start=101, chunk_stop=162, 
                                                  time_chunk_index_start=2840, time_chunk_index_stop=2860, ts_path=ts_LO5750_2_PATH, 
                                                  ts_short_filename=ts_LO5750_2_fn, tone_init_path='/home/matt/ali_drive_mnt/tone_initializations', 
                                                  plot_spacing=1)

62
[ 30 -69  47 ...  31 638 480]
[1.71081261e+09 1.71081286e+09 1.71081287e+09]
[1.71081286e+09 1.71081287e+09 1.71081287e+09]
True
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.926359693983875-0.37664003685495456j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.33510489704851815-0.942180825518171j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.5406898685125007-0.8412220076103185j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j

/home/matt/readout/lea_beammap_work/ali_hdf5_reading/time_chunking/ali_offline_demod.py:1393: RuntimeWarning: divide by zero encountered in log10
  y=np.append(y,20*np.log10(np.abs(test_sweep[1,:])))

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (977,)
len t: 977
len t_fr_start: 950
len sig_fr_start: 950
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (977,)
len t: 977
len t_fr_start: 955
len sig_fr_start: 955
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (977,)
len t: 977
len t_fr_start: 963
len sig_fr_start: 963
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (976,)
len t: 976
len t_fr_start: 953
len sig_fr_start: 953
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (976,)
len t: 976
len t_fr_start: 967
len sig_fr_start: 967
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
shape sig: (976,)
len t: 976
len t_fr_start: 952
len sig_fr_start: 952
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
shape sig: (976,)
len t: 976
len t_fr_start: 963
len sig_fr_start: 963
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
shape sig: (977,)
len t: 977
len t_fr_start: 967
len sig_fr_start: 967
using full_demod_process
5750.0
20240318183441
/home/matt/ali_drive_mnt/tone_initializations/fcenter_5750.0_20240318183441/
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
num of channels: 62
num of tones: 62
looking for delay region
start = 5554333351.562596
stop = 5564352882.812596
delay: 6.925742929600547e-08
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.46231968018257197-0.8867133208178867j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9747685271483708-0.2232180962220487j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.852217457503528+0.5231877341129306j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.7393279589446652+0.6733455050141164j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.9064943495126165-0.4222179464467353j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(-0.4081329958292497-0.9129224817669032j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.06207004547510418-0.998071795741528j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.7682800270137966-0.6401138961869833j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.9981886258289444+0.06016200849143683j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.6733502328080465+0.7393236530622765j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j
 5.77746577e+09+0.j 5.77913265e+09+0.j 5.78366053e+09+0.j
 5.78559756e+09+0.j 5.78769559e+09+0.j 5.78963279e+09+0.j
 5.79097642e+09+0.j 5.79257405e+09+0.j 5.79710682e+09+0.j
 5.79863060e+09+0.j 5.80094445e+09+0.j 5.80310866e+09+0.j
 5.80464232e+09+0.j 5.80583480e+09+0.j 5.80778897e+09+0.j
 5.80871859e+09+0.j 5.81133689e+09+0.j 5.81868162e+09+0.j
 5.81998307e+09+0.j 5.82179064e+09+0.j 5.82386616e+09+0.j
 5.82516571e+09+0.j 5.82708898e+09+0.j 5.82759627e+09+0.j
 5.82853695e+09+0.j 5.83228278e+09+0.j 5.83496833e+09+0.j
 5.83720155e+09+0.j 5.83926588e+09+0.j 5.84020829e+09+0.j
 5.84267064e+09+0.j 5.84436349e+09+0.j 5.84620355e+09+0.j
 5.84877730e+09+0.j 5.85273681e+09+0.j 5.85422200e+09+0.j
 5.85635126e+09+0.j 5.85786519e+09+0.j 5.85918348e+09+0.j
 5.86224159e+09+0.j 5.86443292e+09+0.j 5.86602313e+09+0.j
 5.86953220e+09+0.j 5.87151112e+09+0.j 5.87270856e+09+0.j
 5.87431008e+09+0.j 5.87668808e+09+0.j 5.87884261e+09+0.j
 5.88069222e+09+0.j 5.91154378e+09+0.j 5.92025040e+09+0.j
 5.92149872e+09+0.j 5.92345056e+09+0.j]
(0.013377813127842208+0.9999105130540015j)
6.925742929600547e-08
[5.75860952e+09+0.j 5.76059747e+09+0.j 5.76238005e+09+0.j
 5.76663663e+09+0.j 5.76933591e+09+0.j 5.77097784e+09+0.j
 5.77208668e+09+0.j 5.77395736e+09+0.j 5.77569201e+09+0.j

  0%|          | 0/62 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950

In [12]:
%matplotlib qt

testing_full_function = time_chunk_index_demod_plot(ts_LO4250_2, t_xy_LO4250_2, chunk='some', chunk_start=210, chunk_stop=230,
                                                    time_chunk_index_start=2750, time_chunk_index_stop=2770, ts_path=ts_LO4250_2_PATH, 
                                                    ts_short_filename=ts_LO4250_2_fn, tone_init_path='/home/matt/ali_drive_mnt/tone_initializations', 
                                                    plot_spacing=0.1)

21
[2356 2422 2427 ... 2357 2299 2271]
[1.70985001e+09 1.70985026e+09 1.70985027e+09]
[1.70985026e+09 1.70985027e+09 1.70985027e+09]
True
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
2.9839409722222188
n_phi0: 2.9839409722222188
start index: 23

/home/matt/readout/lea_beammap_work/ali_hdf5_reading/time_chunking/ali_offline_demod.py:1393: RuntimeWarning: divide by zero encountered in log10
  y=np.append(y,20*np.log10(np.abs(test_sweep[1,:])))

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (977,)
len t: 977
len t_fr_start: 954
len sig_fr_start: 954
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.1072443181818103
n_phi0: 3.1072443181818103
start index: 11

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (976,)
len t: 976
len t_fr_start: 965
len sig_fr_start: 965
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.2552083333333246
n_phi0: 3.2552083333333246
start index: 17

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
2.7126736111111063
n_phi0: 2.7126736111111063
start index: 19

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.2552083333333246
n_phi0: 3.2552083333333246
start index: 17

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (976,)
len t: 976
len t_fr_start: 959
len sig_fr_start: 959
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.1072443181818143
n_phi0: 3.1072443181818143
start index: 12

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.029739357864353
n_phi0: 3.029739357864353
start index: 12

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (976,)
len t: 976
len t_fr_start: 964
len sig_fr_start: 964
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.0297393578643605
n_phi0: 3.0297393578643605
start index: 26

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (977,)
len t: 977
len t_fr_start: 951
len sig_fr_start: 951
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
2.9592803030303036
n_phi0: 2.9592803030303036
start index: 19

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
shape sig: (977,)
len t: 977
len t_fr_start: 958
len sig_fr_start: 958
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.0297393578643605
n_phi0: 3.0297393578643605
start index: 18

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.029739357864357
n_phi0: 3.029739357864357
start index: 15

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (975,)
len t: 975
len t_fr_start: 960
len sig_fr_start: 960
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
2.504006410256412
n_phi0: 2.504006410256412
start index: 12

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
shape sig: (977,)
len t: 977
len t_fr_start: 965
len sig_fr_start: 965
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.2552083333333246
n_phi0: 3.2552083333333246
start index: 25

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
shape sig: (976,)
len t: 976
len t_fr_start: 951
len sig_fr_start: 951
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
2.835976957070711
n_phi0: 2.835976957070711
start index: 22

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
shape sig: (976,)
len t: 976
len t_fr_start: 954
len sig_fr_start: 954
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
2.8949481225296365
n_phi0: 2.8949481225296365
start index: 15

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (977,)
len t: 977
len t_fr_start: 962
len sig_fr_start: 962
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.2552083333333246
n_phi0: 3.2552083333333246
start index: 8

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (976,)
len t: 976
len t_fr_start: 968
len sig_fr_start: 968
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.1072443181818143
n_phi0: 3.1072443181818143
start index: 11

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.2552083333333246
n_phi0: 3.2552083333333246
start index: 18

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.1072443181818103
n_phi0: 3.1072443181818103
start index: 20

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (976,)
len t: 976
len t_fr_start: 956
len sig_fr_start: 956
using full_demod_process
4250.0
20240307141217
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240307141217/
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
num of channels: 21
num of tones: 21
looking for delay region
start = 4020292968.75
stop = 4030313476.5625
delay: 3.190635683471356e-08
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9991896802758717+0.04024901030088998j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9498424693757376+0.31272876965543334j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7663216252523242+0.6424571321657472j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.42989546942195106+0.9028786659183394j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.024171192470920345+0.9997078340467948j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.5018325238886261+0.8649648073578321j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9217577780547024+0.3877661648412068j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9919468127598257-0.1266551248691635j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.9357009077010052-0.35279429038395j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.8561385513568778-0.5167463409454843j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.6400546278820475-0.7683294041794663j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.47954544927243825-0.8775170437559007j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.16592339078069018-0.9861386456233415j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.2629237714434779-0.964816609729506j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.630331942421827-0.7763257321271314j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9041286387285882-0.4272603475994351j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.9894671902591591+0.14475731208006393j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.8535949760384689+0.5209372485068482j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.7004059711418988+0.7137446851562353j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(0.30974564547379485+0.9508194545285777j)
3.190635683471356e-08
[4.45072461e+09+0.j 4.45211035e+09+0.j 4.45400405e+09+0.j
 4.45614258e+09+0.j 4.45847980e+09+0.j 4.46098159e+09+0.j
 4.46420831e+09+0.j 4.46682813e+09+0.j 4.46799316e+09+0.j
 4.46890346e+09+0.j 4.47056543e+09+0.j 4.47153530e+09+0.j
 4.47319857e+09+0.j 4.47535719e+09+0.j 4.47743192e+09+0.j
 4.47966341e+09+0.j 4.48259013e+09+0.j 4.48459877e+09+0.j
 4.48583027e+09+0.j 4.48813002e+09+0.j 4.49025816e+09+0.j]
(-0.11147820325812359+0.9937668792017273j)
shape_cals: (21, 3)
[-3.11811197e+03-1337.26832242j  1.73773469e+03   +0.j
 -3.01546038e+00   +0.j        ]
3.2552083333333246
n_phi0: 3.2552083333333246
start index: 14

  0%|          | 0/21 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962

In [32]:
tchunk_4750_1_demod = time_chunk_index_demod_plot(ts_LO4750_1, t_xy_LO4750_1, chunk='some', chunk_start=97, chunk_stop=160, 
                                                  time_chunk_index_start=2840, time_chunk_index_stop=2860, ts_path=ts_LO4750_1_PATH, 
                                                  ts_short_filename=ts_LO4750_1_fn, tone_init_path='/home/matt/ali_drive_mnt/tone_initializations', 
                                                  plot_spacing=1)

64
[-1546 -1653 -1573 ... -1236 -1610 -1059]
[1.71001467e+09 1.71001492e+09 1.71001493e+09]
[1.71001492e+09 1.71001493e+09 1.71001494e+09]
True
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.9006159064811599-0.43461590973308695j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8568016620540817+0.5156461111085423j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.14078201808182522+0.9900406170379116j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9227313614274293+0.3854436854305476j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j

/home/matt/readout/lea_beammap_work/ali_hdf5_reading/time_chunking/ali_offline_demod.py:1393: RuntimeWarning: divide by zero encountered in log10
  y=np.append(y,20*np.log10(np.abs(test_sweep[1,:])))

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
shape sig: (976,)
len t: 976
len t_fr_start: 962
len sig_fr_start: 962
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (977,)
len t: 977
len t_fr_start: 969
len sig_fr_start: 969
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
shape sig: (977,)
len t: 977
len t_fr_start: 975
len sig_fr_start: 975
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
shape sig: (976,)
len t: 976
len t_fr_start: 955
len sig_fr_start: 955
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
shape sig: (977,)
len t: 977
len t_fr_start: 960
len sig_fr_start: 960
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
shape sig: (977,)
len t: 977
len t_fr_start: 966
len sig_fr_start: 966
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
shape sig: (977,)
len t: 977
len t_fr_start: 972
len sig_fr_start: 972
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
shape sig: (977,)
len t: 977
len t_fr_start: 947
len sig_fr_start: 947
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
shape sig: (977,)
len t: 977
len t_fr_start: 953
len sig_fr_start: 953
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
shape sig: (977,)
len t: 977
len t_fr_start: 959
len sig_fr_start: 959
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
shape sig: (977,)
len t: 977
len t_fr_start: 964
len sig_fr_start: 964
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
shape sig: (976,)
len t: 976
len t_fr_start: 969
len sig_fr_start: 969
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (976,)
len t: 976
len t_fr_start: 974
len sig_fr_start: 974
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
shape sig: (976,)
len t: 976
len t_fr_start: 950
len sig_fr_start: 950
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
shape sig: (977,)
len t: 977
len t_fr_start: 956
len sig_fr_start: 956
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
shape sig: (976,)
len t: 976
len t_fr_start: 961
len sig_fr_start: 961
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
shape sig: (977,)
len t: 977
len t_fr_start: 968
len sig_fr_start: 968
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
shape sig: (977,)
len t: 977
len t_fr_start: 974
len sig_fr_start: 974
using full_demod_process
4750.0
20240309114324
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4750.0_20240309114324/
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
num of channels: 64
num of tones: 64
looking for delay region
start = 4538558101.562547
stop = 4548578609.375047
delay: 8.181689598200192e-08
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.10730353647107947+0.9942263077694131j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.6656080092608+0.74630153289932j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9962703158018279+0.08628706654027712j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.7241585864223014-0.6896334836062227j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.19149846208505672-0.9814929133819857j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.7148239500425752-0.6993044547588196j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(0.8470464234693638+0.5315189145155225j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.47345848771940124+0.8808161331438348j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9224478748820655+0.3861216364380029j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j
 4.82849542e+09+0.j 4.83103518e+09+0.j 4.83301681e+09+0.j
 4.83670420e+09+0.j 4.83762612e+09+0.j 4.83882387e+09+0.j
 4.84033403e+09+0.j 4.84186835e+09+0.j 4.84324623e+09+0.j
 4.84562616e+09+0.j 4.84784489e+09+0.j 4.85019729e+09+0.j
 4.85218466e+09+0.j 4.85419252e+09+0.j 4.85612021e+09+0.j
 4.85833410e+09+0.j 4.86052225e+09+0.j 4.86271875e+09+0.j
 4.86523335e+09+0.j]
(-0.9129393741090974-0.408095208500773j)
8.181689598200192e-08
[4.73292080e+09+0.j 4.73454669e+09+0.j 4.73601748e+09+0.j
 4.73766585e+09+0.j 4.73961598e+09+0.j 4.74079030e+09+0.j
 4.74338686e+09+0.j 4.74631178e+09+0.j 4.74763681e+09+0.j
 4.74922568e+09+0.j 4.75364455e+09+0.j 4.75557303e+09+0.j
 4.75784954e+09+0.j 4.75986066e+09+0.j 4.76076363e+09+0.j
 4.76486114e+09+0.j 4.76628897e+09+0.j 4.76785649e+09+0.j
 4.76943029e+09+0.j 4.77121098e+09+0.j 4.77328692e+09+0.j
 4.77513012e+09+0.j 4.77776002e+09+0.j 4.77970296e+09+0.j
 4.78075398e+09+0.j 4.78294345e+09+0.j 4.78510668e+09+0.j
 4.78735663e+09+0.j 4.78931276e+09+0.j 4.79126355e+09+0.j
 4.79189853e+09+0.j 4.80290832e+09+0.j 4.80381741e+09+0.j
 4.80484349e+09+0.j 4.80644031e+09+0.j 4.80806359e+09+0.j
 4.80979859e+09+0.j 4.81068364e+09+0.j 4.81333101e+09+0.j
 4.81604030e+09+0.j 4.81802602e+09+0.j 4.82012286e+09+0.j
 4.82178325e+09+0.j 4.82371954e+09+0.j 4.82631038e+09+0.j

  0%|          | 0/64 [00:00<?, ?it/s]

shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948
shape sig: (976,)
len t: 976
len t_fr_start: 948
len sig_fr_start: 948

In [ ]:
chunks_demodulated=[]

for i in range(len(t_4250_1)):
    t_chunked = t_4250_1[i]
    i_chunked = np.array(I_4250_1[i])
    q_chunked = np.array(Q_4250_1[i])
    demodulated_chunk = tcf.modified_demod_process_for_tchunks(t_chunked, i_chunked, q_chunked, ts_file=ts_LO4250_1_fn, f_sawtooth=15, method='fft', 
                                                             correct_phase_jumps=True, phase_jump_threshold=0.4, n=0, channels='some',
                                                             start_channel=102, stop_channel=105, tone_init_path='/home/matt/ali_drive_mnt/tone_initializations',
                                                             ts_path=ts_LO4250_1_PATH, display_mode='notebook')
    
    chunks_demodulated.append(demodulated_chunk)

#### Where I ended 03/05/25 ***

In [13]:
import time_chunking_functions as tcf

In [14]:
# just looking at what the data is like when I'm demodulating small part (not as small as 2 seconds) 

T, I, Q, ch, file = tcf.read_data(ts_LO4250_1, chunk='some', chunk_start=0, chunk_stop=20)

In [28]:
I[0,1]

-47

In [23]:
len(T)/32

486841.0

In [32]:
T_test_chunk = T[0:486841]
I_test_chunk = I[10, 0:486841]
Q_test_chunk = Q[10, 0:486841]

In [3]:
demod_testing = tcf.modified_demod_process_for_tchunks(t_test_chunk, )

(ts_LO4250_1_fn, f_sawtooth=15, method='fft', correct_phase_jumps=True, 
                                       phase_jump_threshold=0.4, n=0, channels='some', start_channel=0, stop_channel=2, 
                                       tone_init_path='/home/matt/ali_drive_mnt/tone_initializations', ts_path=ts_LO4250_1_PATH, 
                                       display_mode='notebook')

using full_demod_process
4250.0
20240308061355
/home/matt/ali_drive_mnt/tone_initializations/fcenter_4250.0_20240308061355/
[4.09184880e+09+0.j 4.09499819e+09+0.j 4.09772073e+09+0.j]

KeyboardInterrupt:

In [30]:
len(T_test_chunk) == len(I_test_chunk)

True

In [31]:
plt.plot(T_test_chunk, I_test_chunk)